### ISSUE TITLE
API not supported

### ISSUE THREAD

**Issue by hhhc** [TheDMSGroup/mautic-extended-field#11]
Hi,

thanks for this great extension.
As we want to use it hundreds of fields that are synced over 10 installations, we approach extended fields with the API.
When trying to create a field using the REST api, it is always created as a lead object, not extendedfield

Follow REST API documentation to create a field:
https://developer.mautic.org/#create-field
<?php
use Mautic\MauticApi;
use Mautic\Auth\ApiAuth;

$settings = array(
        'userName'   => 'user',
        'password'   => 'pwd',
);
$initAuth = new ApiAuth();
$auth     = $initAuth->newAuth($settings);
$apiUrl   = "https://your-mautic.com";
$api      = new MauticApi();
$fieldApi = $api->newApi("contactFields", $auth, $apiUrl);
$data = array(
    'label' => 'API test field',
    'type' => 'text',
    'object' => 'extendedField',
);
$field = $fieldApi->create($data);
?>

In table lead_fields, any new field created by a API call gets the object "lead".

**Comment by heathdutton** [comment]
Needs to be tested with latest master.

**Comment by hhhc** [comment]
I have tested this with the latest 0.17 release and have found some strange behaviour:

1) I am creating the fields via API and get the results with object = lead
<img width="456" alt="mautic_bug_1" src="https://user-images.githubusercontent.com/961087/37148841-21ff1bea-22cc-11e8-8e6f-0f7bff4007d2.png">

2) This is also what is in the DB, table lead_fields
<img width="1252" alt="mautic_bug_2" src="https://user-images.githubusercontent.com/961087/37148842-221fc7b4-22cc-11e8-920b-246292f8e4ea.png">


3) When I click on edit the field, the object shows up correctly in the UI and the value has been changed in the DB although I did not press save. This has been updated automatically in the DB.

<img width="475" alt="mautic_bug_3" src="https://user-images.githubusercontent.com/961087/37148843-22361e6a-22cc-11e8-8453-ccf846fcbd6a.png">
<img width="1027" alt="mautic_bug_4" src="https://user-images.githubusercontent.com/961087/37148844-224dde10-22cc-11e8-89bf-3afad19c15f2.png">

**Comment by hhhc** [comment]
Most importantly, the process stops after 56 fields created, so running in the same issue as beforehand.

**Comment by scottshipman** [comment]
in the FieldApiController:initialize method, it sets $this-fieldObject based on the value of the URL path. So, if the API path is "fields/contact/new" it will force map object => 'lead'.

`
        if ($this->fieldObject === 'contact') {
            $this->fieldObject = 'lead';
        }
`

what happens if you use a route of "/fields/extendedField/new"

**Comment by hhhc** [comment]
That was it. Using the PHP API library, I created a new file in 
`mautic/api-library/lib/Api/ExtendedFields.php `
containing this code:
```
<?php
/**
 * @package     Mautic
 * @copyright   2014 Mautic, NP. All rights reserved.
 * @author      Mautic
 * @link        http://mautic.org
 * @license     MIT http://opensource.org/licenses/MIT
 */

namespace Mautic\Api;

/**
 * ContactFields Context
 */
class ExtendedFields extends Api
{

    /**
     * {@inheritdoc}
     */
    protected $endpoint = 'fields/extendedFields';

    /**
     * {@inheritdoc}
     */
    protected $listName = 'fields';

    /**
     * {@inheritdoc}
     */
    protected $itemName = 'field';
}

```

Is there a way to make this file being integrated in the official API?
Will continue testing, but thanks for this great plugin.

**Comment by heathdutton** [comment]
At some point we'll make a push to get ExtendedFields into core Mautic. If that goes well, we'll update the API to suit, and your example is really helpful!
