### ISSUE TITLE
Deleting a custom field does not delete values from the DB

### ISSUE THREAD

**Issue by hhhc** [TheDMSGroup/mautic-extended-field#20]
When I delete any extendedFields that has some values the records are still in the database.
In my case it was lead_fields_leads_string_xhref with left-over values.

<img width="286" alt="mautic" src="https://user-images.githubusercontent.com/961087/37165550-368c4912-22fd-11e8-928a-90b1b3be6e79.png">

**Comment by heathdutton** [comment]
This should be corrected in the latest version. Give it a try in dev?

**Comment by heathdutton** [comment]
I stand corrected. Appears to still be a bug if one tries to delete a field with values via the UI.

```SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic_eb_site_0`.`lead_fields_leads_string_secure_xref`, CONSTRAINT `FK_6F66100AEE6485B3` FOREIGN KEY (`lead_field_id`) REFERENCES `lead_fields` (`id`)) at /Users/hd/mautic-eb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic_eb_site_0`.`lead_fields_leads_string_secure_xref`, CONSTRAINT `FK_6F66100AEE6485B3` FOREIGN KEY (`lead_field_id`) REFERENCES `lead_fields` (`id`)) at /Users/hd/mautic-eb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic_eb_site_0`.`lead_fields_leads_string_secure_xref`, CONSTRAINT `FK_6F66100AEE6485B3` FOREIGN KEY (`lead_field_id`) REFERENCES `lead_fields` (`id`)) at /Users/hd/mautic-eb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)
[stacktrace]
#0 /Users/hd/mautic-eb/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
#1 /Users/hd/mautic-eb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1015): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'DELETE FROM lea...', Array)
#2 /Users/hd/mautic-eb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php(241): Doctrine\\DBAL\\Connection->executeUpdate('DELETE FROM lea...', Array, Array)
#3 /Users/hd/mautic-eb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(596): Doctrine\\DBAL\\Connections\\MasterSlaveConnection->executeUpdate('DELETE FROM lea...', Array, Array)
#4 /Users/hd/mautic-eb/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php(281): Doctrine\\DBAL\\Connection->delete('lead_fields', Array, Array)
#5 /Users/hd/mautic-eb/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(580): Doctrine\\DBAL\\Connections\\MasterSlaveConnection->delete('lead_fields', Array, Array)
#6 /Users/hd/mautic-eb/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1094): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->delete(Object(Mautic\\LeadBundle\\Entity\\LeadField))
#7 /Users/hd/mautic-eb/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\\ORM\\UnitOfWork->executeDeletions(Object(Doctrine\\ORM\\Mapping\\ClassMetadata))
#8 /Users/hd/mautic-eb/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\\ORM\\UnitOfWork->commit(NULL)
#9 /Users/hd/mautic-eb/mautic/app/bundles/CoreBundle/Entity/CommonRepository.php(202): Doctrine\\ORM\\EntityManager->flush()
#10 /Users/hd/mautic-eb/plugins/MauticExtendedFieldBundle/Model/ExtendedFieldModel.php(375): Mautic\\CoreBundle\\Entity\\CommonRepository->deleteEntity(Object(Mautic\\LeadBundle\\Entity\\LeadField))
#11 /Users/hd/mautic-eb/mautic/app/bundles/LeadBundle/Controller/FieldController.php(419): MauticPlugin\\MauticExtendedFieldBundle\\Model\\ExtendedFieldModel->deleteEntity(Object(Mautic\\LeadBundle\\Entity\\LeadField))
#12 /Users/hd/mautic-eb/mautic/app/bundles/CoreBundle/Controller/CommonController.php(475): Mautic\\LeadBundle\\Controller\\FieldController->deleteAction('459', '')
#13 [internal function]: Mautic\\CoreBundle\\Controller\\CommonController->executeAction('delete', '459', 0, '')
#14 /Users/hd/mautic-eb/vendor/symfony/http-kernel/HttpKernel.php(142): call_user_func_array(Array, Array)
#15 /Users/hd/mautic-eb/vendor/symfony/http-kernel/HttpKernel.php(62): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#16 /Users/hd/mautic-eb/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /Users/hd/mautic-eb/vendor/symfony/http-kernel/Kernel.php(183): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /Users/hd/mautic-eb/mautic/app/AppKernel.php(133): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /Users/hd/mautic-eb/mautic/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /Users/hd/mautic-eb/mautic/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /Users/hd/mautic-eb/mautic/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /Users/hd/mautic-eb/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /Users/hd/mautic-eb/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
un(Object(Stack\\StackedHttpKernel)).php(34): Stack\
#25 {main}
"}```
