### ISSUE TITLE
Installation prefix not implemented 

### ISSUE THREAD

**Issue by PietkaSmig** [TheDMSGroup/mautic-extended-field#36]
Hi guys, 

There is an option to create table prefix during Mautic installation . It seems your plugin does not support this and sql queries do not work properly (tables are missing) . I'm putting the error message we got: 

[2018-05-17 17:10:23] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException:
"An exception occurred while executing '
SELECT COUNT(l.id) as count FROM mtc_leads l LEFT JOIN mtc_users u ON u.id = l.owner_id LEFT JOIN lead_fields_leads_string_xref string129
    ON (l.id  = string129.lead_id) AND (string129.lead_field_id = 129)'
    :  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic.lead_fields_leads_string_xref' doesn't exist"
    at /home/webhosts/XLCD.com/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53
    {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT COUNT(l.id) as count
    FROM mtc_leads l LEFT JOIN mtc_users u ON u.id = l.owner_id LEFT JOIN lead_fields_leads_string_xref string129 ON (l.id  = string129.lead_id) AND
    (string129.lead_field_id = 129)':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic.lead_fields_leads_string_xref' doesn't exist at
    /home/webhosts/XLCD.com/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53,
    Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic.lead_fields_leads_string_xref'
    doesn't exist at /home/webhosts/XLCD.com/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106,
    PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic.lead_fields_leads_string_xref' doesn't exist at
    /home/webhosts/XLCD.com/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []

Br - PS

**Comment by heathdutton** [comment]
Pretty simple to fix. We'll get around to this in about ~2 weeks. Or feel free to open a PR.

**Comment by heathdutton** [comment]
@PietkaSmig in my testing this worked... The latest version will have this fix in addition to a massive perf improvement.

**Comment by PietkaSmig** [comment]
Hi @heathdutton thanks for the quick fix. We will test this this week and I'll share the results.
