### ISSUE TITLE
Installation not working on version 2.13

### ISSUE THREAD

**Issue by fuschini** [TheDMSGroup/mautic-extended-field#46]
Hi all,

I'm really interested in this feature, but I can't make the installation. Already tried:
* Downloading the files manually
* Clearing the cache
Still doesn't work.

Do you have any success tests using 2.13?

Thanks!

**Comment by heathdutton** [comment]
Do you get any errors in your logs?

Are you on Mautic 2.13.0 or  2.13.1 ?

**Comment by heathdutton** [comment]
Looks like the plugin reload step was missed. Closing task.
