### ISSUE TITLE
(BUG) After migration, custom field type "extended contact field" can not be deleted

### ISSUE THREAD

**Issue by AlbanL74fr** [TheDMSGroup/mautic-extended-field#65]
How to replicate ?
1) Migrate from 2.12.2 to 2.14.1
2) Go to custom fields
3) Search for an extended custom field that already has non-empty values for some contact

Actual result : The extended contact field can not be deleted, and the error below is logged. Any contact that have non-empty value for this contact field also can not be deleted from contact page.

Expected result : It should delete this fields, in any circumstances

In order to delete the custom field, here's what I had to find all my contacts that had a non-empty value for this extended contact field, and replace manually non-empty value by empty value

This is the error message I got :

```mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'DELETE FROM lead_fields WHERE id = ?' with params [44]:  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`troy_mautic_staging`.`lead_fields_leads_string_xref`, CONSTRAINT `FK_552CFEC5EE6485B3` FOREIGN KEY (`lead_field_id`) REFERENCES `lead_fields` (`id`))" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'DELETE FROM lead_fields WHERE id = ?' with params [44]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`troy_mautic_staging`.`lead_fields_leads_string_xref`, CONSTRAINT `FK_552CFEC5EE6485B3` FOREIGN KEY (`lead_field_id`) REFERENCES `lead_fields` (`id`)) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`troy_mautic_staging`.`lead_fields_leads_string_xref`, CONSTRAINT `FK_552CFEC5EE6485B3` FOREIGN KEY (`lead_field_id`) REFERENCES `lead_fields` (`id`)) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`troy_mautic_staging`.`lead_fields_leads_string_xref`, CONSTRAINT `FK_552CFEC5EE6485B3` FOREIGN KEY (`lead_field_id`) REFERENCES `lead_fields` (`id`)) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []```

**Comment by scottshipman** [comment]
This issue is addressed by the PR at https://github.com/TheDMSGroup/mautic-extended-field/pull/55

**Comment by heathdutton** [comment]
This has been merged to master. If you check that branch out and run doctrine:schema:update @AlbanL74fr the issue should be resolved.  Otherwise, a new release will be coming out in a day or so to also resolve some performance issues.
