### ISSUE TITLE
Incompatible with 2.15.0-beta

### ISSUE THREAD

**Issue by heathdutton** [TheDMSGroup/mautic-extended-field#70]
```
[Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]
  Circular reference detected for service "mautic.lead.model.field", path: "mautic.lead.model.field -> mautic.lead.model.list -> mautic.lead.model.lead_segment_service -> mautic.lead.model.lead_segment_filter_factory -> mautic.lead.model.lead_segment_schema_cache -> mautic.lead.model.field".
```

**Comment by carloshmm** [comment]
@heathdutton 
I don't know if this is related but I'm getting this error message on version 2.15.0 (stable):
```[2019-04-04 01:19:44] mautic.CRITICAL: Exception thrown when handling an exception (Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: Circular reference detected for service "mautic.core.subscriber", path: "mautic.core.subscriber -> mautic.user.model.user -> mautic.helper.mailer -> swiftmailer.mailer.default". at /opt/mautic-2.15.0/vendor/symfony/dependency-injection/Container.php line 264) {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceCircularReferenceException(code: 0): Circular reference detected for service \"mautic.core.subscriber\", path: \"mautic.core.subscriber -> mautic.user.model.user -> mautic.helper.mailer -> swiftmailer.mailer.default\". at /opt/mautic-2.15.0/vendor/symfony/dependency-injection/Container.php:264)"} []```
