### ISSUE TITLE
Incompatible with Mautic 2.15.1

### ISSUE THREAD

**Issue by lavita-it** [TheDMSGroup/mautic-extended-field#80]
I Tried using the Plugin with Mautic 2.15.1 and get the following error:

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  You have requested a non-existent service "mautic.lead.model.lead".  

Could not find out which change in Mautic 2.15.1 caused this issue ...

**Comment by lavita-it** [comment]
What I found out so far: it' maybe not an incompatibilty, but it seems to be a conflict with a gdpr plugin, that also overwrites the service "mautic.lead.model.lead". Hmm, so we need to decide which service to use or is there any other workaround?

**Comment by heathdutton** [comment]
Which gdpr plugin? I'm curious why that's needed now since Mautic supports GDPR out of the box now.

**Comment by lavita-it** [comment]
https://www.w-4.ch/de/produkte/mautic-dsgvo

We need an opt-out from the tracking. As far as I know, Mautic does not support this out-of-the-box.

**Comment by heathdutton** [comment]
I believe the opt-out of tracking is a feature of core, just takes the configuration and my not behave exactly the way the plugin does. Since this is an external dependency that we cannot solve I'm closing this task.
